import './globals.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/providers/auth-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import Header from '@/components/shared/header';
import Footer from '@/components/shared/footer';
import { ScrollArea } from '@/components/ui/scroll-area';
import ApolloClientProvider from '@/providers/apollo-client-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'GoodsDesign',
  description: 'Generated by GoodsDesign',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background-secondary antialiased`}
      >
        <ApolloClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <ScrollArea className="h-screen">
                <main className="container mx-auto pt-16">
                  <Header />
                  {children}
                  <Footer />
                </main>
              </ScrollArea>
            </AuthProvider>

            <Toaster richColors position="bottom-right" />
          </ThemeProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
