/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/t-shirt.glb -o src/components/shirt.tsx -r public 
*/

import { Decal, useGLTF, useTexture } from '@react-three/drei';
import { useControls } from 'leva';
import { JSX, useRef, useState } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_2_1: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_20: THREE.Mesh;
  };
  materials: {
    Body_FRONT_2664: THREE.MeshStandardMaterial;
    printable: THREE.MeshStandardMaterial;
    Sleeves_FRONT_2669: THREE.MeshStandardMaterial;
  };
};

export function Shirt(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/t-shirt.glb') as GLTFResult;
  const decalTexture = useTexture('/assets/pray_for_Chimple.jpg');
  const decalRef = useRef(undefined);

  useControls({
    positionY: {
      min: 0.8,
      max: 1.5,
      value: 0,
      step: 0.01,
      onChange: (value: any) => {
        setPosition([0, value, 0]);
      },
    },
    positionX: {
      min: -1.5,
      max: 1.5,
      value: 0,
      step: 0.01,
      onChange: (value: any) => {
        setPosition([value, 1.2, 0]);
      },
    },
    scale: {
      min: 0.3,
      max: 10,
      value: 1,
      step: 0.01,
      onChange: (value: any) => {
        setScale([value, value, value]);
      },
    },
  });

  const [position, setPosition] = useState<[number, number, number]>([
    0, 1.2, 0,
  ]);
  const [scale, setScale] = useState<[number, number, number]>([1, 1, 1]);
  const [rotation, setRotation] = useState<[number, number, number]>([0, 0, 0]);

  return (
    <group {...props} dispose={undefined}>
      <group rotation={[0, 0, 0.022]}>
        <group
          position={[-0.082, -6.842, -0.431]}
          rotation={[-1.59, 0.019, -0.041]}
          scale={5.674}
        >
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <group position={[0, -0.003, -0.018]} rotation={[0.097, 0, 0]}>
              <mesh
                geometry={nodes.Object_2.geometry}
                material={materials.Body_FRONT_2664}
              />
              <mesh
                geometry={nodes.Object_2_1.geometry}
                // material={materials.printable}
              >
                <meshBasicMaterial transparent opacity={0} />
                <Decal
                  ref={decalRef as any}
                  debug // Makes "bounding box" of the decal visible
                  position={position} // Position of the decal
                  scale={scale} // Scale of the decal
                  rotation={rotation} // Rotation of the decal (can be a vector or a degree in radians)
                >
                  <meshBasicMaterial
                    map={decalTexture}
                    transparent
                    polygonOffset
                    polygonOffsetFactor={-1} // The material should take precedence over the original
                  />
                </Decal>
              </mesh>
            </group>
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.Body_FRONT_2664}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.Sleeves_FRONT_2669}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials.Sleeves_FRONT_2669}
              position={[0, -0.003, -0.018]}
              rotation={[0.097, 0, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/t-shirt.glb');
